SELECT U.USER_ID,
	USERNAME,
	TRAINING_ID,
	TRAINING_DATE,
	COUNT(TRAINING_DATE) AS COUNT
FROM PUBLIC.user U
INNER JOIN PUBLIC.Training_details TD ON U.USER_ID = TD.USER_ID
GROUP BY U.USER_ID,
	USERNAME,
	TRAINING_ID,
	TRAINING_DATE
HAVING COUNT (TRAINING_DATE) > 1
ORDER BY TRAINING_DATE DESC;
