services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=stc_assessment'
      - 'POSTGRES_PASSWORD=1234'
  spring:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres


